# Generated by Django 3.0.5 on 2021-01-02 19:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('name', models.CharField(default='profile', max_length=100, primary_key=True, serialize=False)),
                ('battery', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.FloatField(default=0.0)),
                ('latitude', models.FloatField(default=0.0)),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('speed', models.FloatField(default=0.0)),
                ('battery', models.FloatField(default=0.0)),
                ('serial', models.CharField(default='0000', max_length=50)),
                ('android_id', models.CharField(default='0000', max_length=50)),
                ('altitude', models.FloatField(default=0.0)),
                ('precision', models.FloatField(default=0.0)),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='route_poisson_api.Profile')),
            ],
        ),
    ]
